-- MySQL Script generated by MySQL Workbench
-- sáb 03 jun 2023 21:10:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema breshopp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema breshopp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `breshopp` ;
USE `breshopp` ;

-- -----------------------------------------------------
-- Table `breshopp`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `breshopp`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `foto` BLOB NULL,
  `vendas` INT NULL,
  `trocas` INT NULL,
  `suspenso` TINYINT(0) NOT NULL,
  `motivo_suspensao` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `breshopp`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `breshopp`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `breshopp`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `breshopp`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `breshopp`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `breshopp`.`fotos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `foto1` BLOB NOT NULL,
  `foto2` BLOB NULL,
  `foto3` BLOB NULL,
  `foto4` BLOB NULL,
  `foto5` BLOB NULL,
  `foto6` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `breshopp`.`publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `breshopp`.`publicacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `tipo_negociacao` VARCHAR(45) NULL,
  `preco` FLOAT NULL,
  `descricao_produto` VARCHAR(300) NULL,
  `descricao_vendedor` VARCHAR(300) NULL,
  `id_fotos` INT NOT NULL,
  `validada` TINYINT(0) NOT NULL,
  `finalizada` TINYINT(0) NOT NULL,
  `motivo_rejeicao` VARCHAR(100) NULL,
  PRIMARY KEY (`id`, `id_usuario`),
  INDEX `fk_publicacao_fotos1_idx` (`id_fotos` ASC) VISIBLE,
  INDEX `fk_publicacao_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_publicacao_categoria1_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_publicacao_fotos1`
    FOREIGN KEY (`id_fotos`)
    REFERENCES `breshopp`.`fotos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publicacao_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `breshopp`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publicacao_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `breshopp`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `breshopp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `breshopp`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `breshopp`.`user_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `breshopp`.`user_1` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `breshopp`.`user_2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `breshopp`.`user_2` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
